
export const allProjects = [
  {
    published: true,
    title: "Select Risk Services",
    description: "• Freelanced to design and develop a web application to empower organizations with risk assessment and mitigation strategies • Implemented algorithms to calculate industry-specific risks • Provided mitigation recommendations for proactive risk management • Technologies: Django, JavaScript",
    repository: "",
    url: "https://selectriskservices.co.zw",
    _id: "",
    type: "",
    path: "",
    slug: "select-risk-services",
  },
  {
    published: true,
    title: "Taskify",
    description: "• A functional Kanban-style task management application inspired by Trello. It utilizes boards, cards, and intuitive drag-and-drop functionality to help users visualize workflows and manage projects collaboratively • Technologies: TypeScript, NextJS",
    repository: "https://github.com/ranga-mcmil/taskify.git",
    url: "http://62.72.16.100:3002/",
    _id: '',
    type: "",
    path: "",
    slug: "taskify",
  },
  {
    published: true,
    title: "Open Table",
    description:
      "• A full-fledged restaurant reservation system similar to OpenTable. Diners can effortlessly browse menus, search by cuisine, and secure tables at their favorite restaurants. The platform streamlines the reservation process for both diners and restaurants, offering features like real-time table availability and booking confirmation   • Technologies: TypeScript, NextJS",
    repository: "https://github.com/ranga-mcmil/opentable.git",
    url: "http://62.72.16.100:3003",
    _id: "",
    date: new Date(),
    type: "",
    path: "",
    slug: "open-table",
  },
  {
    published: true,
    title: "Product Filters",
    description: "• A product filtering application • Technologies: TypeScript, NextJS",
    repository: "https://github.com/ranga-mcmil/product-filtering.git",
    url: "http://62.72.16.100:3004/",
    _id: '',
    type: "",
    path: "",
    slug: "product-filters",
  },

];
